server:
  port: 8020
spring:

#   datasource:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      host-port: 192.168.1.253:3306
#        username: lovewcx
#      password: Jmb12345678
#   rabbitmq:
#     host: 192.168.142,128       #rabbitmq服务地址
#     port: 5672              #rabbitmq通信端口
#     username: guest    #rabbitmq用户名
#     password: guest     #rabbitmq密码
#     template:
#       # 使用return-callback时必须设置mandatory为true
#       mandatory: true
#       # 消息发送到交换机确认机制,是否确认回调
#       publisher-confirms: true
#       # 消息发送到交换机确认机制，是否返回回调
#        publisher-returns: true
#       listener:
#         simple:
#           # 并发消费者初始化值
#           concurrency: 5
#           # 最大值
#           max-concurrency: 10
#           # 每个消费者每次监听时可拉取处理的消息数量
#           prefetch: 20
#           # 确认模式设置为手动签收
#           acknowledge-mode: manual
#   redis:
#      database: 0
#      host: ilego.club.com
#      port: 6379
#      password:
#      timeout: 3000   # 连接超时时间（毫秒）
#      pool:
#         max-active: 100    # 连接池最大连接数（使用负值表示没有限制）S
#         max-idle: 20    # 连接池中的最大空闲连接
#         min-idle: 5    # 连接池中的最小空闲连接
#         max-wait: 2000    # 连接池最大阻塞等待时间
#   auth-interceptor:
#      path-patterns: /**
#      excludes-path-patterns: /firm/login,/firm/register,/firm/logout,/firm/sendCode,/firmpassword/resetLoginPawwoord
#               ,/swagger-resources/**,/webjars/**
#               ,/v2/**,/swagger-ui.html/**
#               ,/api-docs,/error
#                ,/test/**
#                ,/common/**
#               #,/order/**
#   # 禁止交易
#   no-trade-interceptor:
#      enable: true
#      path-patterns: /order/buy/**,/order/push/**,/order/sell/**,/order/confirmPayment/**,/order/confirmReceive/**
#               ,/order/delete/**
#      excludes-path-patterns:
#
#   filter:
#      cors:
#         allowOrigins: http://localhost:80,http://localhost:8080,http://192.168.1.111:80,http://192.168.1.253:70
#            ,http://192.168.0.106:8080,null,http://localhost,http://192.168.0.114:8080
#   devtools:
#      restart:
#         #热部署是否生效
#         enabled: true
  mvc:
   view:
     prefix: /jsp/
     suffix: .jsp
#swagger:
#   enable: true

#web-socket:
#   enable: ${socket.enable:false}

#token:
#   session:
#      timeout: 86400 # 秒 7 * 24 * 3600 = 604800 不操作登录状态保持时间
#   user:
#      timeout: 3600 # 24 * 3600 = 86400 用户信息过期时间
#
#
#upload:
#   root-path: D:/upload/static
#   module: console
#
#logger:
#   home: E:/logs
#   module: console
#   level: info
#   mapper-level: ${logger.sql:debug}
#   environment: STDOUT
#
#wx:
#  appid: wxe50494ccadbfb776
#  appsecret: 0ff38c2571b202e0bf7382df6b22dcff
  
#  spring.mvc.view.prefix=/jsp/
#  spring.mvc.view.suffix=.jsp
